schema {
  query: QueryRoot
  mutation: MutationRoot
}

type AbbreviatedTitleCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type ActiveRegionH implements PersonTag {
  _Ignored: ID
  region: Region!
}

type AdditionalTypeSpecimenN implements TypeTag {
  _Ignored: ID
  text: String!
  kind: TypeSpecimenKind!
  comment: String
}

enum AgeClass {
  extant
  holocene
  fossil
  ichno
  removed
  track
  egg
  coprolite
  burrow
  bite_trace
  redirect
  recently_extinct
}

type AgeClassCE implements ClassificationEntryTag {
  _Ignored: ID
  age: AgeClass!
}

type AgeN implements TypeTag {
  _Ignored: ID
  age: SpecimenAge!
}

type AlternativeNameCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
  comment: String
}

type AlternativeURLA implements ArticleTag {
  _Ignored: ID
  url: String!
}

type AltitudeN implements TypeTag {
  _Ignored: ID
  altitude: String!
  unit: AltitudeUnit!
}

enum AltitudeUnit {
  m
  ft
}

type Article implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  numericYear: Int
  addmonth: String!
  addday: String!
  addyear: String!
  name: String!
  authorTags: [AuthorTag!]!
  year: String
  title: String
  series: String
  volume: String
  issue: String
  startPage: String
  endPage: String
  url: String
  doi: String
  type: ArticleType
  publisher: String
  Location: String!
  pages: String
  miscData: String!
  path: String
  ids: String
  bools: String
  kind: ArticleKind!
  parent: Article
  tags: [ArticleTag!]!
  citationGroup: CitationGroup
  articleNumber: String
  articleSet(before: String, after: String, first: Int, last: Int): ArticleConnection
  numArticleSet: Int!
  comments(before: String, after: String, first: Int, last: Int): ArticleCommentConnection
  numComments: Int!
  locations(before: String, after: String, first: Int, last: Int): LocationConnection
  numLocations: Int!
  classificationEntries(before: String, after: String, first: Int, last: Int): ClassificationEntryConnection
  numClassificationEntries: Int!
  newNames(before: String, after: String, first: Int, last: Int): NameConnection
  numNewNames: Int!
  nameComments(before: String, after: String, first: Int, last: Int): NameCommentConnection
  numNameComments: Int!
  occurrences(before: String, after: String, first: Int, last: Int): OccurrenceConnection
  numOccurrences: Int!
  orderedNewNames(before: String, after: String, first: Int, last: Int): NameConnection
  numOrderedNewNames: Int!
  rootClassificationEntries(before: String, after: String, first: Int, last: Int): ClassificationEntryConnection
  numRootClassificationEntries: Int!
  partiallySuppressedNames(before: String, after: String, first: Int, last: Int): NameConnection
  numPartiallySuppressedNames: Int!
  fullySuppressedNames(before: String, after: String, first: Int, last: Int): NameConnection
  numFullySuppressedNames: Int!
  conservedNames(before: String, after: String, first: Int, last: Int): NameConnection
  numConservedNames: Int!
  spellingSelections(before: String, after: String, first: Int, last: Int): NameConnection
  numSpellingSelections: Int!
  prioritySelections(before: String, after: String, first: Int, last: Int): NameConnection
  numPrioritySelections: Int!
  priorityReversals(before: String, after: String, first: Int, last: Int): NameConnection
  numPriorityReversals: Int!
  typeDesignations(before: String, after: String, first: Int, last: Int): NameConnection
  numTypeDesignations: Int!
  commissionTypeDesignations(before: String, after: String, first: Int, last: Int): NameConnection
  numCommissionTypeDesignations: Int!
  lectotypeDesignations(before: String, after: String, first: Int, last: Int): NameConnection
  numLectotypeDesignations: Int!
  neotypeDesignations(before: String, after: String, first: Int, last: Int): NameConnection
  numNeotypeDesignations: Int!
  specimenDetails(before: String, after: String, first: Int, last: Int): NameConnection
  numSpecimenDetails: Int!
  locationDetails(before: String, after: String, first: Int, last: Int): NameConnection
  numLocationDetails: Int!
  collectionDetails(before: String, after: String, first: Int, last: Int): NameConnection
  numCollectionDetails: Int!
  citationDetails(before: String, after: String, first: Int, last: Int): NameConnection
  numCitationDetails: Int!
  definitionDetails(before: String, after: String, first: Int, last: Int): NameConnection
  numDefinitionDetails: Int!
  etymologyDetails(before: String, after: String, first: Int, last: Int): NameConnection
  numEtymologyDetails: Int!
  typeSpeciesDetails(before: String, after: String, first: Int, last: Int): NameConnection
  numTypeSpeciesDetails: Int!
  biographies(before: String, after: String, first: Int, last: Int): PersonConnection
  numBiographies: Int!
}

type ArticleComment implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  article: Article!
  kind: ArticleCommentKind!
  date: Int!
  text: String!
}

type ArticleCommentConnection {
  pageInfo: PageInfo!
  edges: [ArticleCommentEdge]!
}

type ArticleCommentEdge {
  node: ArticleComment
  cursor: String!
}

enum ArticleCommentKind {
  dating
  contents
  authorship
  location
  other
}

type ArticleConnection {
  pageInfo: PageInfo!
  edges: [ArticleEdge]!
}

type ArticleEdge {
  node: Article
  cursor: String!
}

enum ArticleIdentifier {
  doi
  pmid
  jstor
  pmc
  hdl
}

enum ArticleKind {
  electronic
  physical
  no_copy
  part
  redirect
  removed
  reference
  alternative_version
}

type ArticleNumberIsSecondaryCG implements CitationGroupTag {
  _Ignored: ID
  comment: String
}

type ArticleNumberRegexCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

interface ArticleTag {
  _Ignored: ID
}

enum ArticleType {
  ERROR
  CHAPTER
  BOOK
  THESIS
  WEB
  MISCELLANEOUS
  SUPPLEMENT
  JOURNAL
  REDIRECT
  PART
}

type AsEmendedByN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type AuthorA implements AuthorTag {
  _Ignored: ID
  person: Person!
}

type AuthorB implements AuthorTag {
  _Ignored: ID
  person: Person!
}

type AuthorN implements AuthorTag {
  _Ignored: ID
  person: Person!
}

interface AuthorTag {
  _Ignored: ID
}

type AuthorityPageLinkN implements TypeTag {
  _Ignored: ID
  url: String!
  confirmed: Boolean!
  page: String!
}

type AuxiliaryNameCE implements ClassificationEntryTag {
  _Ignored: ID
}

type BHLBibliographyCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type BHLWrongPageNumbersA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type BHLYearRangeCG implements CitationGroupTag {
  _Ignored: ID
  start: String
  end: String
}

type BasalT implements TaxonTag {
  _Ignored: ID
  comment: String
}

type BatLitA implements ArticleTag {
  _Ignored: ID
  zoteroId: String!
  zenodoDoi: String
}

type BiblioNoteA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type BiblioNoteCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type BiographyH implements PersonTag {
  _Ignored: ID
  article: Article!
}

type Book implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  authorTags: [AuthorTag!]!
  year: String
  title: String!
  subtitle: String
  pages: String
  isbn: String
  publisher: String
  tags: [BookTag!]!
  citationGroup: CitationGroup
  dewey: String
  loc: String
  data: String
  category: String
}

type BookConnection {
  pageInfo: PageInfo!
  edges: [BookEdge]!
}

type BookEdge {
  node: Book
  cursor: String!
}

type BookEditionB implements BookTag {
  _Ignored: ID
  text: String!
}

interface BookTag {
  _Ignored: ID
}

type BoxJZ implements SpecimenTag {
  _Ignored: ID
  type: BoxType!
  taxon: String!
  description: String!
}

enum BoxType {
  default
  separate
}

type CEConditionCE implements ClassificationEntryTag {
  _Ignored: ID
  status: NomenclatureStatus!
  comment: String
}

enum Calendar {
  gregorian
  julian
  french_republican
}

type CalendarID implements IssueDateTag {
  _Ignored: ID
  calendar: Calendar!
}

type ChildRuleC implements CollectionTag {
  _Ignored: ID
  collection: Collection!
  regex: String!
  taxon: Taxon
  age: AgeClass
}

type CitationDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

type CitationGroup implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  name: String!
  region: Region
  status: CitationGroupStatus!
  type: ArticleType!
  target: CitationGroup
  tags: [CitationGroupTag!]!
  archive: String
  redirects(before: String, after: String, first: Int, last: Int): CitationGroupConnection
  numRedirects: Int!
  patterns(before: String, after: String, first: Int, last: Int): CitationGroupPatternConnection
  numPatterns: Int!
  articleSet(before: String, after: String, first: Int, last: Int): ArticleConnection
  numArticleSet: Int!
  issueDateSet(before: String, after: String, first: Int, last: Int): IssueDateConnection
  numIssueDateSet: Int!
  itemFileSet(before: String, after: String, first: Int, last: Int): ItemFileConnection
  numItemFileSet: Int!
  names(before: String, after: String, first: Int, last: Int): NameConnection
  numNames: Int!
  bookSet(before: String, after: String, first: Int, last: Int): BookConnection
  numBookSet: Int!
  orderedNames(before: String, after: String, first: Int, last: Int): NameConnection
  numOrderedNames: Int!
  orderedArticles(before: String, after: String, first: Int, last: Int): ArticleConnection
  numOrderedArticles: Int!
}

type CitationGroupConnection {
  pageInfo: PageInfo!
  edges: [CitationGroupEdge]!
}

type CitationGroupEdge {
  node: CitationGroup
  cursor: String!
}

type CitationGroupPattern implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  pattern: String!
  citationGroup: CitationGroup!
}

type CitationGroupPatternConnection {
  pageInfo: PageInfo!
  edges: [CitationGroupPatternEdge]!
}

type CitationGroupPatternEdge {
  node: CitationGroupPattern
  cursor: String!
}

enum CitationGroupStatus {
  normal
  deleted
  redirect
  child
}

interface CitationGroupTag {
  _Ignored: ID
}

type ClassificationEntry implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  article: Article!
  name: String!
  rank: Rank!
  status: ClassificationEntryStatus!
  parent: ClassificationEntry
  page: String
  mappedName: Name
  authority: String
  year: String
  citation: String
  typeLocality: String
  rawData: String
  tags: [ClassificationEntryTag!]!
  children(before: String, after: String, first: Int, last: Int): ClassificationEntryConnection
  numChildren: Int!
  occurrenceRecords(before: String, after: String, first: Int, last: Int): OccurrenceRecordConnection
  numOccurrenceRecords: Int!
}

type ClassificationEntryConnection {
  pageInfo: PageInfo!
  edges: [ClassificationEntryEdge]!
}

type ClassificationEntryEdge {
  node: ClassificationEntry
  cursor: String!
}

enum ClassificationEntryStatus {
  valid
  removed
  redirect
}

interface ClassificationEntryTag {
  _Ignored: ID
}

type CollectedByN implements TypeTag {
  _Ignored: ID
  person: Person!
}

type Collection implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  label: String!
  name: String!
  location: Region!
  comment: String
  city: String
  removed: Boolean!
  tags: [CollectionTag!]!
  parent: Collection
  children(before: String, after: String, first: Int, last: Int): CollectionConnection
  numChildren: Int!
  typeSpecimens(before: String, after: String, first: Int, last: Int): NameConnection
  numTypeSpecimens: Int!
  associatedPeople(before: String, after: String, first: Int, last: Int): PersonConnection
  numAssociatedPeople: Int!
  probableSpecimens(before: String, after: String, first: Int, last: Int): NameConnection
  numProbableSpecimens: Int!
  guessedSpecimens(before: String, after: String, first: Int, last: Int): NameConnection
  numGuessedSpecimens: Int!
  sharedSpecimens(before: String, after: String, first: Int, last: Int): NameConnection
  numSharedSpecimens: Int!
  formerSpecimens(before: String, after: String, first: Int, last: Int): NameConnection
  numFormerSpecimens: Int!
  futureSpecimens(before: String, after: String, first: Int, last: Int): NameConnection
  numFutureSpecimens: Int!
  extraSpecimens(before: String, after: String, first: Int, last: Int): NameConnection
  numExtraSpecimens: Int!
}

type CollectionCodeC implements CollectionTag {
  _Ignored: ID
  label: String!
  comment: String!
  specimenRegex: String
}

type CollectionConnection {
  pageInfo: PageInfo!
  edges: [CollectionEdge]!
}

type CollectionDatabaseC implements CollectionTag {
  _Ignored: ID
  citation: Article!
  comment: String
}

type CollectionDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

type CollectionEdge {
  node: Collection
  cursor: String!
}

interface CollectionTag {
  _Ignored: ID
}

type CommentCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type CommentFromDatabaseCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type CommentFromDatabaseOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
}

type CommentFromSourceCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type CommentFromSourceOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
}

type CommentID implements IssueDateTag {
  _Ignored: ID
  text: String!
  optionalSource: Article
}

enum CommentKind {
  taxonomy
  nomenclature
  type_locality
  type_specimen
  availability
  distribution
  etymology
  other
  structured_quote
  type_species
  homonymy
  spelling
  authorship
  automatic_change
  removal
  contents
  definition
  removed
}

type CommissionTypeDesignationN implements TypeTag {
  _Ignored: ID
  opinion: Article!
  type: Name!
  comment: String
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
}

type CommonNameCE implements ClassificationEntryTag {
  _Ignored: ID
  name: String!
  language: SourceLanguage!
}

type ConditionN implements NameTag {
  _Ignored: ID
  status: NomenclatureStatus!
  comment: String
}

type ConditionalMustHaveSpecimenLinksC implements CollectionTag {
  _Ignored: ID
  regex: String!
  taxon: Taxon
  age: AgeClass
}

type ConservedN implements NameTag {
  _Ignored: ID
  opinion: Article!
  comment: String
}

type CoordinateUncertaintyFromSourceOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
}

type CoordinatesFromGeoNamesL implements LocationTag {
  _Ignored: ID
  geonameId: Int!
}

type CoordinatesFromLocationNameL implements LocationTag {
  _Ignored: ID
}

type CoordinatesFromNameL implements LocationTag {
  _Ignored: ID
  name: Name!
  text: String
}

type CoordinatesFromNominatimL implements LocationTag {
  _Ignored: ID
  osmType: String!
  osmId: Int!
  category: String!
  useBoundingBox: Boolean!
}

type CoordinatesFromOccurrenceRecordL implements LocationTag {
  _Ignored: ID
  occurrenceRecord: OccurrenceRecord!
}

type CoordinatesFromPLSSL implements LocationTag {
  _Ignored: ID
  plssId: String!
}

type CoordinatesManualL implements LocationTag {
  _Ignored: ID
  comment: String!
}

type CoordinatesN implements TypeTag {
  _Ignored: ID
  latitude: String!
  longitude: String!
  openstreetmapUrl: String
}

type CoordinatesOR implements OccurrenceRecordTag {
  _Ignored: ID
  latitude: String!
  longitude: String!
  openstreetmapUrl: String
}

type CorrectedNameCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type DateN implements TypeTag {
  _Ignored: ID
  date: String!
}

type DateOR implements OccurrenceRecordTag {
  _Ignored: ID
  date: String!
}

enum DateSource {
  internal
  external
  doi_published_print
  doi_published_online
  doi_published_other
  doi_published
  decision
  jstor
}

type DatingToolsCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type DefinitionDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

type DescriptionDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

type DifferentAuthorityN implements TypeTag {
  _Ignored: ID
  comment: String
}

enum DistributionOrigin {
  native
  introduced
  possibly_introduced
  ancient_introduction
}

enum DistributionPresence {
  resident
  vagrant
  extirpated
  reintroduced
}

type ETMNAL implements LocationTag {
  _Ignored: ID
  id: String!
}

type EditionA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type ElevationOR implements OccurrenceRecordTag {
  _Ignored: ID
  elevation: String!
  unit: AltitudeUnit!
}

enum EmendationJustification {
  inadvertent_error
  removal_of_mark
  incorrect_family_group_name
  prevailing_usage
  conserved_by_the_commission
}

type EnglishCommonNameT implements TaxonTag {
  _Ignored: ID
  name: String!
}

type EtymologyDetailCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type EtymologyDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

type EurobatsA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type ExternalSpecifierN implements TypeTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type ExtraRepositoryN implements TypeTag {
  _Ignored: ID
  repository: Collection!
}

enum FillDataLevel {
  needs_basic_data
  missing_required_fields
  missing_detail
  incomplete_detail
  incomplete_derived_tags
  no_data_from_original
  nothing_needed
}

type FindKindJZ implements SpecimenTag {
  _Ignored: ID
  kind: KindOfFind!
}

type FormerRepositoryN implements TypeTag {
  _Ignored: ID
  repository: Collection!
}

type FullIssueA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type FullySuppressedByN implements NameTag {
  _Ignored: ID
  opinion: Article!
  comment: String
}

type FutureRepositoryN implements TypeTag {
  _Ignored: ID
  repository: Collection!
}

enum GenderArticle {
  art30_1_1
  art30_1_2
  art30_1_3
  art30_1_4_2
  art30_1_4_3
  art30_1_4_4
  art30_1_4_5
  art30_2_1
  art30_2_2
  art30_2_3
  art30_2_4
  bad_transliteration
  unknown_obvious_stem
  stem_expressly_set
  assumed
}

type GenderN implements TypeTag {
  _Ignored: ID
  gender: SpecimenGender!
}

type GeneralDOIA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type GeneralL implements LocationTag {
  _Ignored: ID
}

type GenusCoelebsN implements TypeTag {
  _Ignored: ID
  comments: String
}

type GenusOnlyClassificationA implements ArticleTag {
  _Ignored: ID
}

enum GrammaticalGender {
  masculine
  feminine
  neuter
}

enum Group {
  species
  genus
  family
  high
}

type GuessedRepositoryN implements TypeTag {
  _Ignored: ID
  repository: Collection!
  score: Float!
}

type HDLA implements ArticleTag {
  _Ignored: ID
  text: String!
  urlappend: String
}

type HMWN implements NameTag {
  _Ignored: ID
  number: String!
  name: String!
}

type HabitatN implements TypeTag {
  _Ignored: ID
  text: String!
}

type HomonymData {
  genera: [Name!]!
  homonyms: [PossibleHomonym!]!
}

type HostN implements TypeTag {
  _Ignored: ID
  name: String!
}

type IFAdditionalVolumeIF implements ItemFileTag {
  _Ignored: ID
  text: String!
}

type IFAlternativeUrlIF implements ItemFileTag {
  _Ignored: ID
  url: String!
}

type IFCommentIF implements ItemFileTag {
  _Ignored: ID
  text: String!
}

type ISBNA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type ISSNA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type ISSNCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type ISSNOnlineCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type IgnoreLintA implements ArticleTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintCE implements ClassificationEntryTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintCG implements CitationGroupTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintH implements PersonTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintL implements LocationTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintN implements TypeTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintOR implements OccurrenceRecordTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintR implements RegionTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreLintT implements TaxonTag {
  _Ignored: ID
  label: String!
  comment: String
}

type IgnoreORCIDProfileA implements ArticleTag {
  _Ignored: ID
  orcid: String!
  comment: String
}

type IgnoreORCIDWorkH implements PersonTag {
  _Ignored: ID
  orcid: String!
  doi: String!
  comment: String
}

type IgnorePotentialCitationFromN implements TypeTag {
  _Ignored: ID
  article: Article!
  comment: String
}

type IgnorePotentialCitationsCG implements CitationGroupTag {
  _Ignored: ID
}

type IgnorePreoccupationByN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String!
}

enum IgnoreReason {
  not_interested
  no_access
  already_have
  invalid
}

type IgnoredDoi implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  reason: IgnoreReason
  doi: String!
}

type ImpreciseLocalityN implements TypeTag {
  _Ignored: ID
  comment: String
}

type InPressA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type IncertaeSedisT implements TaxonTag {
  _Ignored: ID
  comment: String
}

type IncludedSpeciesN implements TypeTag {
  _Ignored: ID
  name: Name!
  comment: String
  page: String
  pageLink: String
  classificationEntry: ClassificationEntry
}

type IncompleteA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type IncompletelyDividedR implements RegionTag {
  _Ignored: ID
}

type InconsistentlyBinominalA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type IncorrectGrammarN implements TypeTag {
  _Ignored: ID
  text: String!
}

type IncorrectOriginalSpellingOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type IncorrectSubsequentSpellingOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type InformalCE implements ClassificationEntryTag {
  _Ignored: ID
}

type InitialsOnlyA implements ArticleTag {
  _Ignored: ID
}

type InstitutionH implements PersonTag {
  _Ignored: ID
  institution: Collection!
}

type InternalSpecifierN implements TypeTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type InterpretedTypeLocalityN implements TypeTag {
  _Ignored: ID
  text: String!
}

type InterpretedTypeSpecimenN implements TypeTag {
  _Ignored: ID
  text: String!
}

type InterpretedTypeTaxonN implements TypeTag {
  _Ignored: ID
  text: String!
}

type InvolvedN implements TypeTag {
  _Ignored: ID
  person: Person!
  comment: String
}

type IssueDate implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  gregorianDate: String
  citationGroup: CitationGroup!
  series: String
  volume: String!
  issue: String
  startPage: String
  endPage: String
  date: String!
  tags: [IssueDateTag!]!
}

type IssueDateConnection {
  pageInfo: PageInfo!
  edges: [IssueDateEdge]!
}

type IssueDateEdge {
  node: IssueDate
  cursor: String!
}

interface IssueDateTag {
  _Ignored: ID
}

type IssueRegexCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type ItemFile implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  filename: String!
  title: String
  citationGroup: CitationGroup!
  series: String
  volume: String
  issue: String
  startPage: String
  endPage: String
  url: String
  tags: [ItemFileTag!]!
}

type ItemFileConnection {
  pageInfo: PageInfo!
  edges: [ItemFileEdge]!
}

type ItemFileEdge {
  node: ItemFile
  cursor: String!
}

interface ItemFileTag {
  _Ignored: ID
}

type JSTORA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type JustifiedEmendationOfN implements NameTag {
  _Ignored: ID
  name: Name!
  justification: EmendationJustification!
  comment: String
}

type KeyReferenceT implements TaxonTag {
  _Ignored: ID
  article: Article!
}

enum KindOfFind {
  bottle
  picked_up
  professional
}

type KnownAlternativeYearA implements ArticleTag {
  _Ignored: ID
  year: String!
  comment: String
}

type LSIDA implements ArticleTag {
  _Ignored: ID
  text: String!
  presentInArticle: PresenceStatus!
}

type LSIDCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type LSIDN implements TypeTag {
  _Ignored: ID
  text: String!
}

type LanguageB implements BookTag {
  _Ignored: ID
  language: SourceLanguage!
}

type LectotypeDesignationN implements TypeTag {
  _Ignored: ID
  optionalSource: Article
  lectotype: String!
  valid: Boolean!
  comment: String
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
  year: String
  term: LectotypeDesignationTerm
  isExplicitChoice: Boolean
  isAssumptionOfMonotypy: Boolean
}

enum LectotypeDesignationTerm {
  lectotype
  holotype
  the_type
  other
}

type Location implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  regionPath: [Region!]!
  openstreetmapUrl: String
  name: String!
  minPeriod: Period
  maxPeriod: Period
  minAge: Int
  maxAge: Int
  stratigraphicUnit: StratigraphicUnit
  region: Region!
  comment: String
  latitude: String
  longitude: String
  locationDetail: String
  ageDetail: String
  source: Article
  deleted: LocationStatus!
  tags: [LocationTag!]!
  parent: Location
  aliases(before: String, after: String, first: Int, last: Int): LocationConnection
  numAliases: Int!
  typeLocalities(before: String, after: String, first: Int, last: Int): NameConnection
  numTypeLocalities: Int!
  taxa(before: String, after: String, first: Int, last: Int): OccurrenceConnection
  numTaxa: Int!
  occurrenceRecords(before: String, after: String, first: Int, last: Int): OccurrenceRecordConnection
  numOccurrenceRecords: Int!
  specimenSet(before: String, after: String, first: Int, last: Int): SpecimenConnection
  numSpecimenSet: Int!
  partialTypeLocalities(before: String, after: String, first: Int, last: Int): NameConnection
  numPartialTypeLocalities: Int!
}

type LocationConnection {
  pageInfo: PageInfo!
  edges: [LocationEdge]!
}

type LocationDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
  comment: String
  page: String
  translation: String
  pageLink: String
  classificationEntry: ClassificationEntry
}

type LocationEdge {
  node: Location
  cursor: String!
}

type LocationHintOR implements OccurrenceRecordTag {
  _Ignored: ID
  name: String!
}

enum LocationStatus {
  valid
  deleted
  alias
}

interface LocationTag {
  _Ignored: ID
}

type MDDT implements TaxonTag {
  _Ignored: ID
  id: String!
}

type MandatoryChangeOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type MappedClassificationEntryN implements NameTag {
  _Ignored: ID
  ce: ClassificationEntry!
}

type MaterializeBaseNameAuthorCE implements ClassificationEntryTag {
  _Ignored: ID
  person: Person!
  order: Int!
}

type MaterializeBaseNameCE implements ClassificationEntryTag {
  _Ignored: ID
  originalName: String!
  page: String!
  originalCitation: Article
  verbatimCitation: String
  citationGroup: CitationGroup
  originalRank: Rank
}

type MaterializeCE implements ClassificationEntryTag {
  _Ignored: ID
  parentTaxonId: Int
}

type MaterializeParentCE implements ClassificationEntryTag {
  _Ignored: ID
  ce: ClassificationEntry!
}

type MayHaveIdentifierCG implements CitationGroupTag {
  _Ignored: ID
  identifier: ArticleIdentifier!
  minYear: Int
  maxYear: Int
}

type MisidentificationOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

interface Model {
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
}

type ModelCls {
  callSign: String!
  name: String!
  autocompletions(field: String): [String!]!
  autocomplete(query: String!, field: String, limit: Int): [String!]!
  newest(first: Int, after: String, before: String, last: Int): ModelConnection!
}

type ModelConnection {
  pageInfo: PageInfo!
  edges: [ModelEdge]!
}

type ModelEdge {
  node: Model
  cursor: String!
}

type MolecularDataOR implements OccurrenceRecordTag {
  _Ignored: ID
}

type MustBeExtinctN implements TypeTag {
  _Ignored: ID
  comment: String
}

type MustBePartOfN implements TypeTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type MustHaveAfterCG implements CitationGroupTag {
  _Ignored: ID
  year: String!
}

type MustHaveCG implements CitationGroupTag {
  _Ignored: ID
}

type MustHaveIdentifierCG implements CitationGroupTag {
  _Ignored: ID
  identifier: ArticleIdentifier!
  minYear: Int
  maxYear: Int
}

type MustHavePreciseDateCG implements CitationGroupTag {
  _Ignored: ID
}

type MustHavePreciseTypeLocalityR implements RegionTag {
  _Ignored: ID
}

type MustHaveSeriesCG implements CitationGroupTag {
  _Ignored: ID
  comment: String
}

type MustHaveSpecimenLinksC implements CollectionTag {
  _Ignored: ID
}

type MustHaveURLCG implements CitationGroupTag {
  _Ignored: ID
}

type MustNotBePartOfN implements TypeTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type MustNotIncludeN implements TypeTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type MustUseChildrenA implements ArticleTag {
  _Ignored: ID
}

type MustUseChildrenCollectionC implements CollectionTag {
  _Ignored: ID
}

type MustUseTripletsC implements CollectionTag {
  _Ignored: ID
}

type MutationRoot {
  openArticle(articleId: Int!): OpenArticle
}

type NOWL implements LocationTag {
  _Ignored: ID
  id: String!
}

type Name implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  numericYear: Int
  variantBaseId: Int!
  orderedClassificationEntries(before: String, after: String, first: Int, last: Int): ClassificationEntryConnection
  numOrderedClassificationEntries: Int!
  group: Group!
  rootName: String!
  status: Status!
  taxon: Taxon!
  originalName: String
  correctedOriginalName: String
  nomenclatureStatus: NomenclatureStatus!
  target: Name
  authorTags: [AuthorTag!]!
  originalCitation: Article
  pageDescribed: String
  verbatimCitation: String
  citationGroup: CitationGroup
  year: String
  nameComplex: NameComplex
  speciesNameComplex: SpeciesNameComplex
  type: Name
  typeLocality: Location
  typeSpecimen: String
  collection: Collection
  genusTypeKind: TypeSpeciesDesignation
  speciesTypeKind: SpeciesGroupType
  typeTags: [TypeTag!]!
  originalRank: Rank
  originalParent: Name
  data: String
  tags: [NameTag!]!
  redirects(before: String, after: String, first: Int, last: Int): NameConnection
  numRedirects: Int!
  typifiedNames(before: String, after: String, first: Int, last: Int): NameConnection
  numTypifiedNames: Int!
  originalChildren(before: String, after: String, first: Int, last: Int): NameConnection
  numOriginalChildren: Int!
  comments(before: String, after: String, first: Int, last: Int): NameCommentConnection
  numComments: Int!
  classificationEntries(before: String, after: String, first: Int, last: Int): ClassificationEntryConnection
  numClassificationEntries: Int!
  taxonSet(before: String, after: String, first: Int, last: Int): TaxonConnection
  numTaxonSet: Int!
  fillDataLevel: FillDataLevel
  preoccupiedNames(before: String, after: String, first: Int, last: Int): NameConnection
  numPreoccupiedNames: Int!
  juniorPrimaryHomonyms(before: String, after: String, first: Int, last: Int): NameConnection
  numJuniorPrimaryHomonyms: Int!
  juniorSecondaryHomonyms(before: String, after: String, first: Int, last: Int): NameConnection
  numJuniorSecondaryHomonyms: Int!
  unjustifiedEmendations(before: String, after: String, first: Int, last: Int): NameConnection
  numUnjustifiedEmendations: Int!
  incorrectSubsequentSpellings(before: String, after: String, first: Int, last: Int): NameConnection
  numIncorrectSubsequentSpellings: Int!
  nominaNova(before: String, after: String, first: Int, last: Int): NameConnection
  numNominaNova: Int!
  variants(before: String, after: String, first: Int, last: Int): NameConnection
  numVariants: Int!
  takingPriority(before: String, after: String, first: Int, last: Int): NameConnection
  numTakingPriority: Int!
  nominaOblita(before: String, after: String, first: Int, last: Int): NameConnection
  numNominaOblita: Int!
  mandatoryChanges(before: String, after: String, first: Int, last: Int): NameConnection
  numMandatoryChanges: Int!
  incorrectOriginalSpellings(before: String, after: String, first: Int, last: Int): NameConnection
  numIncorrectOriginalSpellings: Int!
  subsequentUsages(before: String, after: String, first: Int, last: Int): NameConnection
  numSubsequentUsages: Int!
  misidentifications(before: String, after: String, first: Int, last: Int): NameConnection
  numMisidentifications: Int!
  nameCombinations(before: String, after: String, first: Int, last: Int): NameConnection
  numNameCombinations: Int!
  rerankings(before: String, after: String, first: Int, last: Int): NameConnection
  numRerankings: Int!
  selectionsOfPriority(before: String, after: String, first: Int, last: Int): NameConnection
  numSelectionsOfPriority: Int!
  selectionsOfSpelling(before: String, after: String, first: Int, last: Int): NameConnection
  numSelectionsOfSpelling: Int!
  reversalsOfPriority(before: String, after: String, first: Int, last: Int): NameConnection
  numReversalsOfPriority: Int!
  justifiedEmendations(before: String, after: String, first: Int, last: Int): NameConnection
  numJustifiedEmendations: Int!
  designatedAsType(before: String, after: String, first: Int, last: Int): NameConnection
  numDesignatedAsType: Int!
  commissionDesignatedAsType(before: String, after: String, first: Int, last: Int): NameConnection
  numCommissionDesignatedAsType: Int!
}

type NameCombinationOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type NameComment implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  name: Name!
  kind: CommentKind!
  date: Int!
  text: String!
  source: Article
  page: String
}

type NameCommentConnection {
  pageInfo: PageInfo!
  edges: [NameCommentEdge]!
}

type NameCommentEdge {
  node: NameComment
  cursor: String!
}

type NameComplex implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  label: String!
  stem: String
  sourceLanguage: SourceLanguage!
  codeArticle: GenderArticle!
  gender: GrammaticalGender!
  comment: String
  stemRemove: String!
  stemAdd: String!
  endings(before: String, after: String, first: Int, last: Int): NameEndingConnection
  numEndings: Int!
  names(before: String, after: String, first: Int, last: Int): NameConnection
  numNames: Int!
}

type NameConnection {
  pageInfo: PageInfo!
  edges: [NameEdge]!
}

type NameEdge {
  node: Name
  cursor: String!
}

type NameEnding implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  nameComplex: NameComplex!
  ending: String!
  comment: String!
}

type NameEndingConnection {
  pageInfo: PageInfo!
  edges: [NameEndingEdge]!
}

type NameEndingEdge {
  node: NameEnding
  cursor: String!
}

interface NameTag {
  _Ignored: ID
}

type NamedAfterN implements TypeTag {
  _Ignored: ID
  person: Person!
}

enum NamingConvention {
  unspecified
  pinyin
  japanese
  dutch
  burmese
  spanish
  ancient
  organization
  hungarian
  vietnamese
  german
  general
  russian
  turkish
  chinese
  korean
  mongolian
  ukrainian
  other
  english
  english_peer
  french
  italian
  portuguese
}

type NearbyRegionL implements LocationTag {
  _Ignored: ID
  region: Region!
}

type NeedsPrioritySelectionN implements NameTag {
  _Ignored: ID
  over: Name!
  reason: SelectionReason!
}

type NeedsTranslationA implements ArticleTag {
  _Ignored: ID
  language: SourceLanguage!
}

type NeotypeDesignationN implements TypeTag {
  _Ignored: ID
  optionalSource: Article
  neotype: String!
  valid: Boolean!
  comment: String
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
}

type NoAgeN implements TypeTag {
  _Ignored: ID
  source: Article!
}

type NoCollectorN implements TypeTag {
  _Ignored: ID
  source: Article!
}

type NoDateN implements TypeTag {
  _Ignored: ID
  source: Article!
}

type NoEtymologyN implements TypeTag {
  _Ignored: ID
  source: Article!
}

type NoGenderN implements TypeTag {
  _Ignored: ID
  source: Article!
}

type NoLocationN implements TypeTag {
  _Ignored: ID
  source: Article!
}

type NoOrganN implements TypeTag {
  _Ignored: ID
  source: Article!
}

type NoOriginalParentN implements TypeTag {
  _Ignored: ID
}

type NoSpecimenN implements TypeTag {
  _Ignored: ID
  source: Article!
}

interface Node {
  id: ID!
}

type NomenNovumForN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type NomenOblitumN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
  optionalSource: Article
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
}

type NomenclatureCommentsN implements TypeTag {
  _Ignored: ID
  text: String!
  record: String!
}

type NomenclatureDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

enum NomenclatureStatus {
  available
  nomen_nudum
  fully_suppressed
  not_based_on_a_generic_name
  infrasubspecific
  unpublished
  incorrect_subsequent_spelling
  unjustified_emendation
  before_1758
  hypothetical_concept
  teratological
  hybrid_as_such
  informal
  work_of_extant
  zoological_formula
  unlisted
  not_latin_alphabet
  inconsistently_binominal
  not_used_as_valid
  not_used_as_genus_plural
  based_on_a_suppressed_name
  not_published_with_a_generic_name
  multiple_words
  no_type_specified
  anonymous_authorship
  conditional
  variety_or_form
  not_explicitly_new
  mandatory_change
  ites_name
  hybrid_name
  art_13_nomen_oblitum
  variant
  justified_emendation
  preoccupied
  based_on_homonym
  partially_suppressed
  nomen_novum
  incorrect_original_spelling
  type_not_treated_as_valid
  reranking
  subsequent_usage
  not_intended_as_a_scientific_name
  collective_group
  not_nominative_singular
  as_emended
  rejected_by_fiat
  unpublished_thesis
  unpublished_electronic
  unpublished_pending
  unpublished_supplement
  name_combination
  misidentification
  placed_on_index
}

type NominalGenusT implements TaxonTag {
  _Ignored: ID
  genus: Name!
}

type NonOriginalA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type NotPreoccupiedByN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type NotUsedAsValidN implements NameTag {
  _Ignored: ID
  comment: String
}

type ORCIDH implements PersonTag {
  _Ignored: ID
  text: String!
}

enum ObservationKind {
  visual
  acoustic
}

type ObservationKindOR implements OccurrenceRecordTag {
  _Ignored: ID
  kind: ObservationKind!
}

type Occurrence implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  taxon: Taxon!
  location: Location!
  comment: String!
  status: OccurrenceStatus!
  source: Article
}

enum OccurrenceBasis {
  voucher
  observation
  listing
}

type OccurrenceConnection {
  pageInfo: PageInfo!
  edges: [OccurrenceEdge]!
}

type OccurrenceEdge {
  node: Occurrence
  cursor: String!
}

type OccurrenceRecord implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  classificationEntry: ClassificationEntry!
  localityText: String!
  page: String
  basis: OccurrenceBasis!
  rawData: String
  taxon: Taxon
  location: Location
  tags: [OccurrenceRecordTag!]!
  status: OccurrenceRecordStatus!
}

type OccurrenceRecordConnection {
  pageInfo: PageInfo!
  edges: [OccurrenceRecordEdge]!
}

type OccurrenceRecordEdge {
  node: OccurrenceRecord
  cursor: String!
}

enum OccurrenceRecordStatus {
  valid
  deleted
  alias
}

interface OccurrenceRecordTag {
  _Ignored: ID
}

enum OccurrenceStatus {
  valid
  rejected
  occurrence_dubious
  introduced
  extirpated
  vagrant
  classification_dubious
}

enum OccurrenceValidity {
  valid
  rejected
  occurrence_dubious
  classification_dubious
  incidental
}

type OnlineBioH implements PersonTag {
  _Ignored: ID
  text: String!
}

type OpenArticle {
  ok: Boolean
}

type OpenStreetMapR implements RegionTag {
  _Ignored: ID
  osmType: String!
  osmId: Int!
  category: String!
}

type OrganN implements TypeTag {
  _Ignored: ID
  organ: SpecimenOrgan!
  detail: String
  condition: String
}

type OriginFromSourceOR implements OccurrenceRecordTag {
  _Ignored: ID
  origin: DistributionOrigin!
  comment: String
}

type OriginalCitationCE implements ClassificationEntryTag {
  _Ignored: ID
}

type OriginalCombinationCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type OriginalLanguageB implements BookTag {
  _Ignored: ID
  language: SourceLanguage!
}

type OriginalPageDescribedCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type OriginalTypificationN implements TypeTag {
  _Ignored: ID
  basis: SpeciesBasis!
  source: Article!
  comment: String
}

type PBDBL implements LocationTag {
  _Ignored: ID
  id: String!
}

type PLSSL implements LocationTag {
  _Ignored: ID
  text: String!
  plssId: String!
  comment: String
}

type PMCA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type PMIDA implements ArticleTag {
  _Ignored: ID
  text: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type PageLinkCE implements ClassificationEntryTag {
  _Ignored: ID
  url: String!
  page: String!
}

type PageRegexCG implements CitationGroupTag {
  _Ignored: ID
  startPageRegex: String
  pagesRegex: String
  allowStandard: Boolean!
}

type PartLocationA implements ArticleTag {
  _Ignored: ID
  parent: Article!
  startPage: Int!
  endPage: Int!
  comment: String
}

type PartialClassificationA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type PartialPageA implements ArticleTag {
  _Ignored: ID
}

type PartialTaxonN implements TypeTag {
  _Ignored: ID
  taxon: Taxon!
}

type PartialTypeLocalityN implements TypeTag {
  _Ignored: ID
  location: Location!
}

type PartiallySuppressedByN implements NameTag {
  _Ignored: ID
  opinion: Article!
  comment: String
}

type PendingRejectionN implements NameTag {
  _Ignored: ID
  comment: String
}

type Period implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  locations(before: String, after: String, first: Int, last: Int): LocationConnection
  numLocations: Int!
  name: String!
  parent: Period
  prev: Period
  next: Period
  minAge: Int
  maxAge: Int
  minPeriod: Period
  maxPeriod: Period
  system: PeriodSystem!
  rank: PeriodRank!
  comment: String!
  region: Region
  deleted: Boolean!
  children(before: String, after: String, first: Int, last: Int): PeriodConnection
  numChildren: Int!
  nextForeign(before: String, after: String, first: Int, last: Int): PeriodConnection
  numNextForeign: Int!
  prevForeign(before: String, after: String, first: Int, last: Int): PeriodConnection
  numPrevForeign: Int!
  childrenMin(before: String, after: String, first: Int, last: Int): PeriodConnection
  numChildrenMin: Int!
  childrenMax(before: String, after: String, first: Int, last: Int): PeriodConnection
  numChildrenMax: Int!
  stratigraphicUnitsMin(before: String, after: String, first: Int, last: Int): StratigraphicUnitConnection
  numStratigraphicUnitsMin: Int!
  stratigraphicUnitsMax(before: String, after: String, first: Int, last: Int): StratigraphicUnitConnection
  numStratigraphicUnitsMax: Int!
  locationsMin(before: String, after: String, first: Int, last: Int): LocationConnection
  numLocationsMin: Int!
  locationsMax(before: String, after: String, first: Int, last: Int): LocationConnection
  numLocationsMax: Int!
  hasLocations: Boolean
}

type PeriodConnection {
  pageInfo: PageInfo!
  edges: [PeriodEdge]!
}

type PeriodEdge {
  node: Period
  cursor: String!
}

enum PeriodRank {
  age
  epoch
  period
  era
  eon
  _bed
  _member
  _formation
  _group
  _supergroup
  other_chronostratigraphy
  subage
  biozone
  _subgroup
  zonation
}

enum PeriodSystem {
  gts
  nalma
  elma
  alma
  salma
  _lithostratigraphy
  aulma
  local_biostratigraphy
  aflma
}

type PermanentlyReplacedSecondaryHomonymOfN implements NameTag {
  _Ignored: ID
  name: Name!
  optionalSource: Article
  isInUse: Boolean!
  comment: String
  replacementName: Name
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
}

type Person implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  aliases(before: String, after: String, first: Int, last: Int): PersonConnection
  numAliases: Int!
  familyName: String!
  givenNames: String
  initials: String
  suffix: String
  tussenvoegsel: String
  birth: String
  death: String
  tags: [PersonTag!]!
  namingConvention: NamingConvention!
  type: PersonType!
  target: Person
  bio: String
  olId: String
  personSet(before: String, after: String, first: Int, last: Int): PersonConnection
  numPersonSet: Int!
  patronyms(before: String, after: String, first: Int, last: Int): NameConnection
  numPatronyms: Int!
  collected(before: String, after: String, first: Int, last: Int): NameConnection
  numCollected: Int!
  involved(before: String, after: String, first: Int, last: Int): NameConnection
  numInvolved: Int!
  articles(before: String, after: String, first: Int, last: Int): ArticleConnection
  numArticles: Int!
  books(before: String, after: String, first: Int, last: Int): BookConnection
  numBooks: Int!
  names(before: String, after: String, first: Int, last: Int): NameConnection
  numNames: Int!
  patronymsAll(before: String, after: String, first: Int, last: Int): NameConnection
  numPatronymsAll: Int!
  collectedAll(before: String, after: String, first: Int, last: Int): NameConnection
  numCollectedAll: Int!
  involvedAll(before: String, after: String, first: Int, last: Int): NameConnection
  numInvolvedAll: Int!
  articlesAll(before: String, after: String, first: Int, last: Int): ArticleConnection
  numArticlesAll: Int!
  booksAll(before: String, after: String, first: Int, last: Int): BookConnection
  numBooksAll: Int!
  namesAll(before: String, after: String, first: Int, last: Int): NameConnection
  numNamesAll: Int!
  orderedNames(before: String, after: String, first: Int, last: Int): NameConnection
  numOrderedNames: Int!
  orderedArticles(before: String, after: String, first: Int, last: Int): ArticleConnection
  numOrderedArticles: Int!
}

type PersonConnection {
  pageInfo: PageInfo!
  edges: [PersonEdge]!
}

type PersonEdge {
  node: Person
  cursor: String!
}

interface PersonTag {
  _Ignored: ID
}

enum PersonType {
  unchecked
  checked
  soft_redirect
  hard_redirect
  deleted
  alias
}

type PhyloCodeNumberN implements TypeTag {
  _Ignored: ID
  number: Int!
}

type PhylogeneticDefinitionN implements TypeTag {
  _Ignored: ID
  type: PhylogeneticDefinitionType!
  source: Article!
  comment: String
}

enum PhylogeneticDefinitionType {
  minimum_clade
  maximum_clade
  apomorphy
  minimum_crown_clade
  maximum_crown_clade
  maximum_total_clade
  pan_clade
  other
}

type PlacedOnIndexA implements ArticleTag {
  _Ignored: ID
  source: Article!
  comment: String!
}

type PossibleHomonym {
  name: Name!
  exactNameMatch: Boolean!
  fuzzyNameMatch: Boolean!
  sameOriginalGenus: Boolean!
  sameCurrentGenus: Boolean!
  editDistance: Int
  relatedGenus: Boolean!
  isCurrentHomonym: Boolean!
}

type PredecessorCG implements CitationGroupTag {
  _Ignored: ID
  cg: CitationGroup!
}

type PreoccupiedByN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type PresenceFromSourceOR implements OccurrenceRecordTag {
  _Ignored: ID
  presence: DistributionPresence!
  comment: String
}

enum PresenceStatus {
  absent
  to_be_determined
  probably_absent
  present
  inferred
}

type PrimaryHomonymOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type ProbableRepositoryN implements TypeTag {
  _Ignored: ID
  repository: Collection!
  reasoning: String
}

type PublicationDateA implements ArticleTag {
  _Ignored: ID
  source: DateSource!
  date: String!
  comment: String
  calendar: Calendar
}

type PublishedBeforeA implements ArticleTag {
  _Ignored: ID
  article: Article!
  comment: String!
}

type QueryRoot {
  node(id: ID!): Node
  byCallSign(callSign: String!, oid: String!): [Model]
  documentation(path: String!): String
  modelCls(callSign: String!): ModelCls!
  search(query: String!, before: String, after: String, first: Int, last: Int): SearchResultConnection
  speciesHomonyms(genusName: String!, rootName: String!): HomonymData
  regionByLabel(label: String): [Region]
  region(oid: Int): Region
  citationGroupByLabel(label: String): [CitationGroup]
  citationGroup(oid: Int): CitationGroup
  citationGroupPatternByLabel(label: String): [CitationGroupPattern]
  citationGroupPattern(oid: Int): CitationGroupPattern
  personByLabel(label: String): [Person]
  person(oid: Int): Person
  articleByLabel(label: String): [Article]
  article(oid: Int): Article
  articleComment(oid: Int): ArticleComment
  issueDateByLabel(label: String): [IssueDate]
  issueDate(oid: Int): IssueDate
  periodByLabel(label: String): [Period]
  period(oid: Int): Period
  stratigraphicUnitByLabel(label: String): [StratigraphicUnit]
  stratigraphicUnit(oid: Int): StratigraphicUnit
  locationByLabel(label: String): [Location]
  location(oid: Int): Location
  taxonByLabel(label: String): [Taxon]
  taxon(oid: Int): Taxon
  collectionByLabel(label: String): [Collection]
  collection(oid: Int): Collection
  classificationEntryByLabel(label: String): [ClassificationEntry]
  classificationEntry(oid: Int): ClassificationEntry
  itemFileByLabel(label: String): [ItemFile]
  itemFile(oid: Int): ItemFile
  speciesNameComplexByLabel(label: String): [SpeciesNameComplex]
  speciesNameComplex(oid: Int): SpeciesNameComplex
  nameComplexByLabel(label: String): [NameComplex]
  nameComplex(oid: Int): NameComplex
  nameEndingByLabel(label: String): [NameEnding]
  nameEnding(oid: Int): NameEnding
  speciesNameEndingByLabel(label: String): [SpeciesNameEnding]
  speciesNameEnding(oid: Int): SpeciesNameEnding
  nameByLabel(label: String): [Name]
  name(oid: Int): Name
  nameCommentByLabel(label: String): [NameComment]
  nameComment(oid: Int): NameComment
  ignoredDoiByLabel(label: String): [IgnoredDoi]
  ignoredDoi(oid: Int): IgnoredDoi
  occurrence(oid: Int): Occurrence
  occurrenceRecordByLabel(label: String): [OccurrenceRecord]
  occurrenceRecord(oid: Int): OccurrenceRecord
  bookByLabel(label: String): [Book]
  book(oid: Int): Book
  specimenByLabel(label: String): [Specimen]
  specimen(oid: Int): Specimen
  specimenComment(oid: Int): SpecimenComment
}

enum Rank {
  subspecies
  species
  species_group
  subgenus
  other_subgeneric
  genus
  division
  infratribe
  subtribe
  tribe
  infrafamily
  subfamily
  family
  superfamily
  hyperfamily
  other_family
  unranked_family
  parvorder
  infraorder
  suborder
  semiorder
  order
  superorder
  magnorder
  subcohort
  cohort
  supercohort
  infraclass
  subclass
  class_
  superclass
  infraphylum
  subphylum
  phylum
  superphylum
  infrakingdom
  subkingdom
  kingdom
  superkingdom
  domain
  root
  unranked
  informal
  other
  variety
  form
  infrasubspecific
  synonym
  aberratio
  morph
  natio
  subvariety
  other_species
  informal_species
  mutation
  race
  synonym_species
  synonym_genus
  synonym_family
  synonym_high
}

type RawPageRegexA implements ArticleTag {
  _Ignored: ID
  regex: String!
  comment: String
}

type ReassessOccurrencesT implements TaxonTag {
  _Ignored: ID
  region: Region!
  source: Article!
  cutoffYear: Int
  comment: String
}

type RedirectOccurrencesT implements TaxonTag {
  _Ignored: ID
  region: Region!
  target: Taxon!
  source: Article!
  cutoffYear: Int
  comment: String
}

type RedirectTargetOR implements OccurrenceRecordTag {
  _Ignored: ID
  record: OccurrenceRecord!
}

type ReferencedUsageCE implements ClassificationEntryTag {
  _Ignored: ID
  ce: ClassificationEntry!
  comment: String
}

type Region implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  name: String!
  comment: String
  parent: Region
  kind: RegionKind!
  tags: [RegionTag!]!
  children(before: String, after: String, first: Int, last: Int): RegionConnection
  numChildren: Int!
  citationGroups(before: String, after: String, first: Int, last: Int): CitationGroupConnection
  numCitationGroups: Int!
  periods(before: String, after: String, first: Int, last: Int): PeriodConnection
  numPeriods: Int!
  stratigraphicUnits(before: String, after: String, first: Int, last: Int): StratigraphicUnitConnection
  numStratigraphicUnits: Int!
  locations(before: String, after: String, first: Int, last: Int): LocationConnection
  numLocations: Int!
  collections(before: String, after: String, first: Int, last: Int): CollectionConnection
  numCollections: Int!
  specimenSet(before: String, after: String, first: Int, last: Int): SpecimenConnection
  numSpecimenSet: Int!
  hasCollections: Boolean
  hasCitationGroups: Boolean
  hasLocations: Boolean
  hasPeriods: Boolean
  hasTypeLocalities: Boolean
  hasAssociatedPeople: Boolean
  hasStratigraphicUnits: Boolean
  associatedPeople(before: String, after: String, first: Int, last: Int): PersonConnection
  numAssociatedPeople: Int!
}

type RegionConnection {
  pageInfo: PageInfo!
  edges: [RegionEdge]!
}

type RegionEdge {
  node: Region
  cursor: String!
}

enum RegionKind {
  continent
  country
  subnational
  planet
  other
  county
  island
  state
  province
  department
  region
  canton
  prefecture
  territory
  supranational
  sea
  redirect
  deleted
}

interface RegionTag {
  _Ignored: ID
}

type RegionalOriginT implements TaxonTag {
  _Ignored: ID
  region: Region!
  origin: DistributionOrigin!
  source: Article!
  comment: String
}

type RegionalPresenceT implements TaxonTag {
  _Ignored: ID
  region: Region!
  presence: DistributionPresence!
  source: Article!
  comment: String
}

type RejectedDOIA implements ArticleTag {
  _Ignored: ID
  doi: String!
}

type RejectedLSIDN implements TypeTag {
  _Ignored: ID
  text: String!
}

type RejectedN implements NameTag {
  _Ignored: ID
  opinion: Article!
  comment: String
}

type RepositoryCG implements CitationGroupTag {
  _Ignored: ID
  url: String!
  comment: String
}

type RepositoryN implements TypeTag {
  _Ignored: ID
  repository: Collection!
}

type RerankingOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type ReversalOfPriorityN implements NameTag {
  _Ignored: ID
  over: Name!
  opinion: Article!
  comment: String
}

type ReviewedInLightOfOR implements OccurrenceRecordTag {
  _Ignored: ID
  article: Article!
  taxon: Taxon!
  comment: String!
}

type SearchResult {
  model: Model
  context: String
  highlight: String
}

type SearchResultConnection {
  pageInfo: PageInfo!
  edges: [SearchResultEdge]!
}

type SearchResultEdge {
  node: SearchResult
  cursor: String!
}

type SecondaryHomonymOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type SelectionOfPriorityN implements NameTag {
  _Ignored: ID
  overName: Name
  optionalSource: Article
  comment: String
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
  overCe: ClassificationEntry
}

type SelectionOfSpellingN implements NameTag {
  _Ignored: ID
  optionalSource: Article
  comment: String
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
}

enum SelectionReason {
  primary_homonymy
  secondary_homonymy
  synonymy
  mixed_homonymy
  reverse_mixed_homonymy
}

type SeriesRegexCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type SkipExtraBHLBibliographiesCG implements CitationGroupTag {
  _Ignored: ID
}

type SourceDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

enum SourceLanguage {
  latin
  greek
  other
  english
  french
  german
  spanish
  portuguese
  russian
  arabic
  chinese
  mongolian
  japanese
  thai
  korean
  hungarian
  vietnamese
  italian
  dutch
  papiamento
  catalan
  modern_greek
  hebrew
  aramaic
  sanskrit
  hindi
  old_english
  bulgarian
  albanian
  frisian
  norwegian
  danish
  swedish
  finnish
}

enum SpeciesBasis {
  explicit_holotype
  implicit_holotype
  explicit_syntypes
  implicit_syntypes
  unclear
}

enum SpeciesGroupType {
  holotype
  lectotype
  neotype
  syntypes
  nonexistent
}

type SpeciesNameComplex implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  label: String!
  stem: String
  kind: SpeciesNameKind!
  masculineEnding: String!
  feminineEnding: String!
  neuterEnding: String!
  comment: String
  target: SpeciesNameComplex
  children(before: String, after: String, first: Int, last: Int): SpeciesNameComplexConnection
  numChildren: Int!
  endings(before: String, after: String, first: Int, last: Int): SpeciesNameEndingConnection
  numEndings: Int!
  names(before: String, after: String, first: Int, last: Int): NameConnection
  numNames: Int!
}

type SpeciesNameComplexConnection {
  pageInfo: PageInfo!
  edges: [SpeciesNameComplexEdge]!
}

type SpeciesNameComplexEdge {
  node: SpeciesNameComplex
  cursor: String!
}

type SpeciesNameEnding implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  nameComplex: SpeciesNameComplex!
  ending: String!
  comment: String!
  fullNameOnly: Boolean!
}

type SpeciesNameEndingConnection {
  pageInfo: PageInfo!
  edges: [SpeciesNameEndingEdge]!
}

type SpeciesNameEndingEdge {
  node: SpeciesNameEnding
  cursor: String!
}

enum SpeciesNameKind {
  adjective
  noun_in_apposition
  genitive
  genitive_adjective
  non_latin
  ambiguous_noun
  patronym_masculine
  patronym_feminine
  patronym_masculine_plural
  patronym_feminine_plural
  patronym_latin
  unknown
}

type Specimen implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  taxon: Taxon!
  region: Region!
  location: Location
  taxonText: String!
  locationText: String!
  date: String!
  description: String!
  link: String
  tags: [SpecimenTag!]!
  comments(before: String, after: String, first: Int, last: Int): SpecimenCommentConnection
  numComments: Int!
}

enum SpecimenAge {
  embryo
  juvenile
  subadult
  adult
  larva
}

type SpecimenComment implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  specimen: Specimen!
  date: Int!
  text: String!
}

type SpecimenCommentConnection {
  pageInfo: PageInfo!
  edges: [SpecimenCommentEdge]!
}

type SpecimenCommentEdge {
  node: SpecimenComment
  cursor: String!
}

type SpecimenConnection {
  pageInfo: PageInfo!
  edges: [SpecimenEdge]!
}

type SpecimenDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
  classificationEntry: ClassificationEntry
}

type SpecimenDetailOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
}

type SpecimenEdge {
  node: Specimen
  cursor: String!
}

enum SpecimenGender {
  male
  female
  hermaphrodite
  unknown
}

type SpecimenLinkPrefixC implements CollectionTag {
  _Ignored: ID
  prefix: String!
}

enum SpecimenOrgan {
  skin
  skull
  postcranial_skeleton
  mandible
  tooth
  in_alcohol
  other
  maxilla
  antler
  humerus
  femur
  ulna
  radius
  tibia
  fibula
  vertebra
  pelvis
  dentary
  caudal_tube
  osteoderm
  coracoid
  whole_animal
  egg
  horn_core
  frontlet
  petrosal
  tarsometatarsus
  scapula
  carpal
  hyoid
  rib
  manus
  pes
  astragalus
  calcaneum
  clavicle
  navicular
  sternum
  baculum
  tissue_sample
  shell
  skeleton
  limb
  girdle
  scapulocoracoid
  carpometacarpal
  patella
  ilium
  ischium
  pubis
  metacarpal
  metatarsal
  phalanx_manus
  phalanx_pes
  premaxilla
  metapodial
  tibiotarsus
  furcula
  phalanx
  interclavicle
  gastralia
  prepubis
  predentary
  palate
}

type SpecimenRegexC implements CollectionTag {
  _Ignored: ID
  regex: String!
}

interface SpecimenTag {
  _Ignored: ID
}

enum Status {
  valid
  synonym
  dubious
  nomen_dubium
  species_inquirenda
  spurious
  removed
  redirect
  composite
  hybrid
  unavailable
}

type StratigraphicUnit implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  name: String!
  parent: StratigraphicUnit
  prev: StratigraphicUnit
  minPeriod: Period
  maxPeriod: Period
  rank: StratigraphicUnitRank!
  comment: String!
  region: Region
  deleted: Boolean!
  children(before: String, after: String, first: Int, last: Int): StratigraphicUnitConnection
  numChildren: Int!
  next(before: String, after: String, first: Int, last: Int): StratigraphicUnitConnection
  numNext: Int!
  locations(before: String, after: String, first: Int, last: Int): LocationConnection
  numLocations: Int!
  hasLocations: Boolean
}

type StratigraphicUnitConnection {
  pageInfo: PageInfo!
  edges: [StratigraphicUnitEdge]!
}

type StratigraphicUnitEdge {
  node: StratigraphicUnit
  cursor: String!
}

enum StratigraphicUnitRank {
  bed
  member
  formation
  group
  supergroup
  other_lithostratigraphy
  subgroup
}

type StratigraphyDetailN implements TypeTag {
  _Ignored: ID
  text: String!
}

type StructuredDataCE implements ClassificationEntryTag {
  _Ignored: ID
  label: String!
  text: String!
}

type StructuredVerbatimCitationN implements TypeTag {
  _Ignored: ID
  volume: String
  issue: String
  startPage: String
  endPage: String
  series: String
  url: String
}

type SubsequentUsageOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type TakesPriorityOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
  optionalSource: Article
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
  isInPrevailingUsage: Boolean
}

type Taxon implements Node & Model {
  id: ID!
  oid: Int!
  callSign: String!
  pageTitle: String!
  redirectUrl: String
  modelCls: ModelCls!
  namesMissingField(field: String!, before: String, after: String, first: Int, last: Int): NameConnection
  numNamesMissingField(field: String!): Int!
  rank: Rank!
  validName: String!
  age: AgeClass!
  parent: Taxon
  data: String
  comments: String
  isPageRoot: Boolean!
  baseName: Name!
  tags: [TaxonTag!]!
  children(before: String, after: String, first: Int, last: Int): TaxonConnection
  numChildren: Int!
  names(before: String, after: String, first: Int, last: Int): NameConnection
  numNames: Int!
  occurrences(before: String, after: String, first: Int, last: Int): OccurrenceConnection
  numOccurrences: Int!
  occurrenceRecords(before: String, after: String, first: Int, last: Int): OccurrenceRecordConnection
  numOccurrenceRecords: Int!
  specimenSet(before: String, after: String, first: Int, last: Int): SpecimenConnection
  numSpecimenSet: Int!
  class_: Taxon
  order: Taxon
  family: Taxon
}

type TaxonConnection {
  pageInfo: PageInfo!
  edges: [TaxonEdge]!
}

type TaxonCountJZ implements SpecimenTag {
  _Ignored: ID
  count: Int!
  taxon: String!
}

type TaxonEdge {
  node: Taxon
  cursor: String!
}

interface TaxonTag {
  _Ignored: ID
}

type TaxonomicSplitFromOR implements OccurrenceRecordTag {
  _Ignored: ID
  record: OccurrenceRecord!
}

type TextualOriginalRankN implements TypeTag {
  _Ignored: ID
  text: String!
}

type TextualRankCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

type TransliteratedFamilyNameH implements PersonTag {
  _Ignored: ID
  text: String!
}

type TreatAsEquivalentToN implements TypeTag {
  _Ignored: ID
  name: Name!
}

type TreatedAsDubiousCE implements ClassificationEntryTag {
  _Ignored: ID
}

type TypeCatalogC implements CollectionTag {
  _Ignored: ID
  citation: Article!
  coverage: String!
}

type TypeDesignationN implements TypeTag {
  _Ignored: ID
  optionalSource: Article
  type: Name!
  comment: String
  page: String
  verbatimCitation: String
  citationGroup: CitationGroup
  pageLink: String
}

type TypeLocalityN implements TypeTag {
  _Ignored: ID
  text: String!
}

type TypeLocalityValidityN implements TypeTag {
  _Ignored: ID
  validity: OccurrenceValidity!
  comment: String
}

enum TypeSpeciesDesignation {
  original_designation
  monotypy
  absolute_tautonymy
  linnaean_tautonymy
  subsequent_monotypy
  subsequent_designation
  implicit
  misidentification
  designated_by_the_commission
  undesignated
}

type TypeSpeciesDetailN implements TypeTag {
  _Ignored: ID
  text: String!
  source: Article!
}

type TypeSpecimenDataCE implements ClassificationEntryTag {
  _Ignored: ID
  text: String!
}

enum TypeSpecimenKind {
  holotype
  lectotype
  neotype
  syntype
  paratype
  paralectotype
  nontype
  uncertain
}

type TypeSpecimenLinkForN implements TypeTag {
  _Ignored: ID
  url: String!
  specimen: String!
  suffix: String
}

type TypeSpecimenLinkN implements TypeTag {
  _Ignored: ID
  url: String!
}

interface TypeTag {
  _Ignored: ID
}

type URLCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type URLPatternCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type UnavailableElectronicA implements ArticleTag {
  _Ignored: ID
  comment: String
}

type UnavailableVersionOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type UnjustifiedEmendationOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type UnplacedL implements LocationTag {
  _Ignored: ID
  comment: String
}

type ValidUseN implements NameTag {
  _Ignored: ID
  source: Article!
  comment: String
}

type ValidityAssessmentOR implements OccurrenceRecordTag {
  _Ignored: ID
  validity: OccurrenceValidity!
  comment: String
}

type ValidityFromSourceOR implements OccurrenceRecordTag {
  _Ignored: ID
  validity: OccurrenceValidity!
  comment: String
}

type VariantOfN implements NameTag {
  _Ignored: ID
  name: Name!
  comment: String
}

type VarietyOrFormN implements NameTag {
  _Ignored: ID
  comment: String
}

type VerbatimCoordinatesOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
}

type VerbatimDateOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
}

type VerbatimElevationOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
}

type VerbatimNameN implements TypeTag {
  _Ignored: ID
  text: String!
}

type VerbatimParentCE implements ClassificationEntryTag {
  _Ignored: ID
  ce: ClassificationEntry!
}

type VolumeRegexCG implements CitationGroupTag {
  _Ignored: ID
  text: String!
}

type VoucherOR implements OccurrenceRecordTag {
  _Ignored: ID
  text: String!
  collection: Collection!
}

type WikiH implements PersonTag {
  _Ignored: ID
  text: String!
}

type YearRangeCG implements CitationGroupTag {
  _Ignored: ID
  start: String!
  end: String
}

type _RawCollectorN implements TypeTag {
  _Ignored: ID
  text: String!
}
